#!/bin/bash

#${JENKINS_HOME}/status/updateStatus $DSTATUS $LOGFILE ${JOB_BASE_NAME}

XDIR=$(dirname $0)
cd $XDIR
DSTATUS=$1; shift
LOGFILE=$1; shift
JOB_BASE_NAME=$*

git pull
pushd jobs

rm -f "${JOB_BASE_NAME}.svg"
ln -s ../images/$DSTATUS.svg "${JOB_BASE_NAME}.svg"
touch "${JOB_BASE_NAME}.$DSTATUS"
[ -s $LOGFILE ] && cp $LOGFILE "${JOB_BASE_NAME}.log"
git add "${JOB_BASE_NAME}.*"

popd

## rewrite readme. 
JOBS=$( cd jobs ; ls -1 *.svg| sed 's/.svg//' )

cat >README.md<<XXX

## Synopsis

This file shows the status of public cen.ai tracked projects as of $(date).

## Modules 

| MODULE & Logfile | Status | Test Pass | Test Fail| Build | Attempt|
| --- | --- | --- | --- | ---  | --- |
XXX


TODAY=$(date +'%Y-%m-%d ')

for JOBNAME in $JOBS
do

    # get time stamps on each file
    TP=$([ -e "jobs/$JOBNAME.TESTPASS"  ] && stat -c %y "jobs/$JOBNAME.TESTPASS"| sed 's/:..\..*$//'| sed "s/$TODAY//;s/ .*$$//")
    TF=$([ -e "jobs/$JOBNAME.TESTFAIL"  ] && stat -c %y "jobs/$JOBNAME.TESTFAIL"| sed 's/:..\..*$//')
    BP=$([ -e "jobs/$JOBNAME.BUILDPASS" ] && stat -c %y "jobs/$JOBNAME.BUILDPASS"| sed 's/:..\..*$//')
    BD=$([ -e "jobs/$JOBNAME.svg"       ] && stat -c %y "jobs/$JOBNAME.svg"| sed 's/:..\..*$//')
    # get real file
    MF=$(readlink -f "jobs/$JOBNAME.svg" | sed "s|$(pwd)||")
    # get formatting for log file
    LF=$([ -e jobs/$JOBNAME.log ] && echo "[$JOBNAME](jobs/$JOBNAME.log)" || echo "$JOBNAME")
    LM=$([ -e "jobs/$JOBNAME.log"       ] && grep 'tests passed' "jobs/$JOBNAME.log" | tail -1) 

    # print
cat >>README.md<<YYY
| $LF | ![Status]($MF) | $LM | $TP | $TF | $BP  | $BD |
YYY


done

cat >>README.md <<ZZZ
( Times are currently EST/EDT GMT-5/-4) 

## Contributors

Ed Guy.

## License

MIT license. 

ZZZ

git commit -am "${JOB_BASE_NAME} $DSTATUS "
git push

